sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yangjunming123
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wx5d16fd022e88d889
    secret: 85322a9bb5f53c14293accf19d8f8784